#!/usr/bin/env bash
set -euo pipefail           # 腳本任何一步出錯就立即結束

# ---------- 檢查參數 ----------
if (( $# != 1 )); then
    echo "Usage: $0 <FILE>.sd"
    exit 1
fi

SRC="$1"

# 檔案存在嗎？
if [[ ! -f "$SRC" ]]; then
    echo "Error: '$SRC' not found."
    exit 1
fi

# 必須是 .sd 結尾（只比對小寫，如需大小寫皆可自行改寫）
if [[ "${SRC##*.}" != "sd" ]]; then
    echo "Error: file must have .sd extension"
    exit 1
fi

# ---------- 執行 parser ----------
ABS_SRC="$(realpath "$SRC" 2>/dev/null || readlink -f "$SRC")"
# ↑ macOS 預設沒有 realpath；如果失敗就用 readlink -f（Linux）

./parser "$ABS_SRC"

# ---------- 組 jasm → class ----------
BASE="$(basename "$SRC" .sd)"    # 只留純檔名（不含副檔名）
JFILE="${BASE}.jasm"

if [[ ! -f "$JFILE" ]]; then
    echo "Error: expected '$JFILE' not generated by parser"
    exit 1
fi

./javaa "$JFILE" > Assembling.log 2>&1

# ---------- 執行 Java ----------
# 若產生 package 再自行加 -cp 與 fully-qualified name
java "$BASE"
